Created popup window
10-menachi/portfolio pull request #15
Opened 2023-04-13 12:55 UTC by 10-menachi

Added:
- Dynamic card generation
- Responsive Popup Window

2023-04-13 13:02 UTC, emmiiorji requested changes
Hi @10-menachi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220870678-4f45b7ed-1d79-4e6a-9338-da59224b2cbc.gif'/>
</div>

You have submitted a pair programming project without commits from other member(s) of the team. Kindly ensure that all members of the team participate in the project, evidenced by their commits.

Should you have issues making contacts with your partner, kindly include a screenshot of your conversation with the student success team giving you permission to work alone for the week.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-14 08:41 UTC, Kossi-stack requested changes
## Hi @ Team,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly add your partner's social handle in the Readme.
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-14 08:41 UTC, Kossi-stack commented on index.html
> -            <li>JavaScript</li>
- [ ] Kindly fix the space between the technologies
- Your Design
<img width="479" alt="Screenshot 2023-04-14 at 01 18 15" src="https://user-images.githubusercontent.com/81444338/231990851-92dcc9b4-7d33-42d0-bbf8-9d5d1cb14483.png">
- Figma Design
- Figma Design

<img width="648" alt="Screenshot 2023-04-14 at 01 18 53" src="https://user-images.githubusercontent.com/81444338/231990901-142354b6-9cd8-4bcb-8f04-db76a2981f61.png">

2023-04-14 10:36 UTC, AdnanOlarmmi approved these changes
Hi @10-menachi,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice one fixing required changes.
- Working app.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 10:39 UTC, merged